[SW-2567] Fix CoxPH docs example for Scala and Python (#2531)
* Create sw_coxph.rst

Current example fails for 
```
org.apache.spark.sql.AnalysisException: cannot resolve '`label`' given input columns: [start, transplant, stop, age, event, year, id, surgery];;
'Project [start#2305, stop#2306, event#2307, age#2308, year#2309, surgery#2310, transplant#2311, id#2312, 'label]
+- Relation[start#2305,stop#2306,event#2307,age#2308,year#2309,surgery#2310,transplant#2311,id#2312] csv
```

* Corrected "Isolation Forest" to "CoxPH"

* Updated example with split of heart.csv & corrected scala formatting

Updated frames with a split of heart.csv to train/test 
& corrected scala formatting to work in cli/jupyter notebook

Note that heart.csv is SW smalldata folder is the same as the heart.csv example as H2O 3 (http://docs.h2o.ai/h2o/latest-stable/h2o-docs/data-science/coxph.html#examples)

(cherry picked from commit 7b6ea690fc977d06d13448074c99b11c94ca3e7c)