[SW-206] Finalize support of Spark 2.0
Include the following changes in:
  - Core
    - DataFrame transformation now supports both Vector classes provided by `mllib.linalg` and `ml.linalg` packages (the classes
      are not compatible)
    - Introducing `SparkSessionSupport` to create/obtain a new Spark Session (alternative to `SparkContextSupport`)
    - LogUtil moved to org.apache.spark.h2o.utils package to have access to Spark Logging class
    - Using `DataSet<Row>` instead of alias `DataFrame` in `JavaH2OContext`
    - Remove deprecated API `H2OContext#asSchemaRDD`
    - Fix incompatible Scala API in SVM model
  - Tests
    - H2OConf needs to verify `SparkConf` and inject REPL configuration (`spark.repl.class.outputDir`) via calling `H2OConf.checkSparkConf` !
    - Using SparkSession to get SQLContext
    - Remove warning from unit tests by using `ConcurrentHashMap[K, Unit]`
    - Limit spark failures and fail test if error in spark infrastructure occurs (by setting `spark.task.maxFailures=1` and `spark.rpc.numRetries=1`)
    - Removed unused `PerTestSparkTestContext` class
  - Script tests
    - Fix evaluation of terms via `intp#valueOfTerm` which does not work in Spark2.0 REPL.
      The workaround is using `intp#eval` method to get value of given variable
  - Yarn integration tests
    - Disable timeline service for yarn integration tests because it requires Jersey lib v1 which was removed from Spark2.0
      See: https://www.hackingnote.com/en/spark/trouble-shooting/NoClassDefFoundError-ClientConfig/
  - Build
    - Environment variable "SPARK_SCALA_VERSION" needs to be setup to run tests via Spark lancher (fork a process approach)
    - Assembly: removing guava library from Sparkling Water assembly due to collision with Spark embedded guava
  - Docs
    - Remove all references to Spark version less than 2.0
    - Replace all references to Scala 2.10 by 2.11 (new default for Spark 2.0)